services:
  php-apache-environment:
    image: mystorepanel:1.0.0
    container_name: mystorepanel
    build:
      context: ./
      dockerfile: docker/Dockerfile
    volumes:
      - ./html:/var/www/html/
    ports:
      - '${APP_PORT}:80'
    env_file:
      - .env
    environment:
      # Ensure this is disabled in production to avoid security/performance issues.
      - XDEBUG_LOG_LEVEL=${XDEBUG_LOG_LEVEL}
